apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beanimageclassifier
  template:
    metadata:
      labels:
        app: beanimageclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/siddharth-project-13788/imgwebapp:v1
        ports:
        - containerPort: 8501
